apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prefix }}-deployment
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: {{ .Values.prefix }}-container
        image: {{ .Values.image }}
        ports:
        - containerPort: {{ .Values.port }}
        envFrom:
        - secretRef:
            name: {{ .Values.prefix }}-secret
