apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prefix }}-load-balancer
  labels:
    app: {{ .Values.app }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.port }}
  selector:
    app: {{ .Values.app }}
