apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.prefix }}-secret
data:
  DATABASE_USERNAME: {{ required "database.username is required" .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ required "database.password is required" .Values.database.password | b64enc}}
  DATABASE_FQDN: {{ required "database.fqdn is required" .Values.database.fqdn | b64enc}}
